### ISSUE TITLE
能不能搞个uni-app版本

### ISSUE THREAD

**Issue by joel785454405** [xylink-com/xylink-mp-sdk-demo#8]
国内好用的小程序框架uni-app求个

**Comment by luojinghui** [comment]
@joel785454405 
uni-app版本demo我们预计会在6月下旬提供示例程序。

自己实现的话，可以参考小程序提供的UI SDK组件代码，这部分的逻辑会在uni-app上实现。原因是UI SDK组件是使用微信小程序语法实现的，如果需要在uni-app上用，需要转化为相应的语法。

**Comment by joel785454405** [comment]
> @joel785454405 uni-app版本demo我们预计会在6月下旬提供示例程序。
> 
> 自己实现的话，可以参考小程序提供的UI SDK组件代码，这部分的逻辑会在uni-app上实现。原因是UI SDK组件是使用微信小程序语法实现的，如果需要在uni-app上用，需要转化为相应的语法。

感谢回复，我改造了UI部分，但v3.8 sdk.js部分报错，能否指点一下
![image](https://github.com/xylink-com/xylink-mp-sdk-demo/assets/32213119/4ffd6625-c96f-4119-8cce-07a042c5d898)

**Comment by luojinghui** [comment]
> > @joel785454405 uni-app版本demo我们预计会在6月下旬提供示例程序。
> > 自己实现的话，可以参考小程序提供的UI SDK组件代码，这部分的逻辑会在uni-app上实现。原因是UI SDK组件是使用微信小程序语法实现的，如果需要在uni-app上用，需要转化为相应的语法。
> 
> 感谢回复，我改造了UI部分，但v3.8 sdk.js部分报错，能否指点一下 ![image](https://user-images.githubusercontent.com/32213119/243533069-4ffd6625-c96f-4119-8cce-07a042c5d898.png)

看上面的截图，应该是你用了uniapp的wxcomponents模式，引入了小鱼的UI组件，这种模式经过我们的测试，是不支持的。主要是uniapp的兼容问题。

可行的思路是：
单独在uniapp项目安装小鱼小程序SDK库，创建uniapp的page，在page中引入core sdk库（不涉及UI组件）：
```ts
import XYRTC from '@xylink/xy-mp-sdk';

// 创建client实例，伪代码
XYClient = XYRTC.createClient({...});
```

创建实例后，可以执行登录/呼叫等操作，UI部分自行在uniapp上处理即可，api文档部分可以参考小鱼开发者中心的说明；

需要注意的时，由于使用了live-pusher和live-player组件作为推拉流，需要对接client中上报的推拉流地址，这块可以参考UI SDK组件里面的逻辑，很大部分是可以复用的，比较简单

**Comment by joel785454405** [comment]
> 
呼叫等确实可用，但是初始化时会报错，对打包有影响，这个方案貌似只能停留在开发环境
![image](https://github.com/xylink-com/xylink-mp-sdk-demo/assets/32213119/28902489-e3ed-4d2a-9fb7-4ce9542c5866)

**Comment by luojinghui** [comment]
我们使用的最新的SDK版本，在uniapp上测试没有遇到问题；
可以提供下你们的使用信息：
1、小程序sdk版本是什么？
2、是否使用了uniapp的wxcomponents模式？

**Comment by joel785454405** [comment]
> 我们使用的最新的SDK版本，在uniapp上测试没有遇到问题； 可以提供下你们的使用信息： 1、小程序sdk版本是什么？ 2、是否使用了uniapp的wxcomponents模式？

1. v3.8
2. 没有使用wxcomponents

直接引入node_modules 和 编译后的miniprogram_npm
初始化第一步就出现了这个问题

`import XYRTC from '@xylink/xy-mp-sdk';

// 创建client实例，伪代码
XYClient = XYRTC.createClient({...});`

就只有这两步，就出现了这个问题

**Comment by luojinghui** [comment]
应该是需要使用小程序SDK的非UI模式，不会存在miniprogram_npm才对；

这里可以提供一个线上v3.8.6版本的参考程序，基于非UI模式实现，仅供参考：
[xysdk-uniapp-test.zip](https://github.com/xylink-com/xylink-mp-sdk-demo/files/11705134/xysdk-uniapp-test.zip)

小鱼预计在6月中下旬提供支持TS版本的SDK和对应的uniapp+ts+非UI模式的示例程序，到时候需要以对应项目为准；

**Comment by joel785454405** [comment]
> 应该是需要使用小程序SDK的非UI模式，不会存在miniprogram_npm才对；
> 
> 这里可以提供一个线上v3.8.6版本的参考程序，基于非UI模式实现，仅供参考： [xysdk-uniapp-test.zip](https://github.com/xylink-com/xylink-mp-sdk-demo/files/11705134/xysdk-uniapp-test.zip)
> 
> 小鱼预计在6月中下旬提供支持TS版本的SDK和对应的uniapp+ts+非UI模式的示例程序，到时候需要以对应项目为准；

**Comment by joel785454405** [comment]
感谢提供的测试参考

**Comment by 94ashui** [comment]
> 应该是需要使用小程序SDK的非UI模式，不会存在miniprogram_npm才对；
> 
> 这里可以提供一个线上v3.8.6版本的参考程序，基于非UI模式实现，仅供参考： [xysdk-uniapp-test.zip](https://github.com/xylink-com/xylink-mp-sdk-demo/files/11705134/xysdk-uniapp-test.zip)
> 
> 小鱼预计在6月中下旬提供支持TS版本的SDK和对应的uniapp+ts+非UI模式的示例程序，到时候需要以对应项目为准；

会有 uni-app 的 UI 模式示例么？

**Comment by luojinghui** [comment]
> > 应该是需要使用小程序SDK的非UI模式，不会存在miniprogram_npm才对；
> > 这里可以提供一个线上v3.8.6版本的参考程序，基于非UI模式实现，仅供参考： [xysdk-uniapp-test.zip](https://github.com/xylink-com/xylink-mp-sdk-demo/files/11705134/xysdk-uniapp-test.zip)
> > 小鱼预计在6月中下旬提供支持TS版本的SDK和对应的uniapp+ts+非UI模式的示例程序，到时候需要以对应项目为准；
> 
> 会有 uni-app 的 UI 模式示例么？

暂时没有提供非小程序框架的UI组件功能，可以考虑基于非UI模式集成。
